export default [
  { path: '/', component: '@/pages/index' },
  { path: '/contexttest', component: '@/pages/context-test' },
  { path: '/tabel', component: '@/pages/tabelCom' },
  { path: '/tabelgroup', component: '@/pages/tabelGroup' },
  { path: '/tabelgroup1', component: '@/pages/tabelGroup1' },
  { path: '/tabelgroup3', component: '@/pages/tabelGroup3' },
  { path: '/tabelgroup4', component: '@/pages/tabelGroup4' },
  { path: '/kucun', component: '@/pages/StatisticalReport' },
  { path: '/modal', component: '@/pages/modaltest' },
  { path: '/derivedState', component: '@/pages/derivedStateFromProp' },
  { path: '/hocref', component: '@/pages/hoc-ref/hoc-ref.js' },
  { path: '/hocre2', component: '@/pages/hoc-ref2/hoc-ref2.js' },
  { path: '/hoc', component: '@/pages/hoc/hoc.js' },
  { path: '/filelet', component: '@/pages/file-let/file-let.js' },
  { path: '/addtable', component: '@/pages/addtable' },
  { path: '/addtablearr', component: '@/pages/addtable-arr' },
  { path: '/formtable', component: '@/pages/formTable' },
  { path: '/swiper', component: '@/pages/zoumadeng' },
  { path: '/swiper2', component: '@/pages/zoumadeng-daping' },
  { path: '/swiper3', component: '@/pages/zoumadeng-daping2' },
  { path: '/swiper4', component: '@/pages/zoumadeng-daping4' },
  { path: '/effectref', component: '@/pages/effect-ref' },
  { path: '/forwardRef', component: '@/pages/forwardRef' },
  // { path: '/app1', component: '@/micro/app1' },
  // { path: '/app2', component: '@/micro/app2' },
];
